from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')

if GetDepend(['FDT_USING_LIBFDT']):
	src += Glob('libfdt/*.c')

CPPPATH = [cwd + '/../inc']

group = DefineGroup('FDT', src, depend = ['PKG_USING_FDT'], CPPPATH = CPPPATH)

Return('group')